version: "3.9"

services:
  molaeng_back:
    build:
      context: ./molaeng_back
    container_name: molaeng_back
    ports:
      - "8080:8080"
    volumes:
      - "/home/ubuntu/tmp:/tmp"
  molaeng_front:
    build:
      context: ./molaeng_front
    container_name: molaeng_front
    ports:
      - "8081:80"