version: "3.9"

services:
  molaeng_back:
    build:
      context: ./molaeng_back
    container_name: molaeng_back
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-container:3306/molaeng"
      SPRING_DATASOURCE_USERNAME: "ssafy"
      SPRING_DATASOURCE_PASSWORD: "ssafyA604!"

  molaeng_front:
    build:
      context: ./molaeng_front
    container_name: molaeng_front
    ports:
      - "8081:80"

  mysql:
    image: mysql
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "/home/ubuntu/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "molaengA604!"
      MYSQL_DATABASE: "molaeng"
      MYSQL_USER: "ssafy"
      MYSQL_PASSWORD: "ssafyA604!"
      TZ: "Asia/Seoul"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"

  redis:
    image: redis
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "/home/ubuntu/redis:/data"